### ISSUE TITLE
Comparison order

### ISSUE THREAD

**Issue by zerkms** [jurassix/react-immutable-render-mixin#3]
As a micro-nano optimization, how about to check `state` before `props`?

From my perspective `state` is what changed more frequently and is more likely to change.

Yep, I understand it's pretty much subjective, but I think it worth mentioning.

**Comment by jurassix** [comment]
Yeah, I can see how order could be gamed. I guess the real question would be what is more common, state or props? Since this is a **PureRenderMixin** for immutable data, this would imply that the component doesn't use state and is purely rendered from props. 

I'll leave this open for now for others to comment and for myself to ponder. I may even put together some perf tests to see what optimizations we can make.

**Comment by jurassix** [comment]
Closing - please reopen if community feels strongly a change is needed.
